baseURL = "http://stefan-lesser.com/"
languageCode = "en-us"
title = "Stefan Lesser"
theme = "lithium"

tags = ["blog"]
features = ["blog", "google analytics"]
min_version = 0.15

[author]
name = "Stefan Lesser"
homepage = "http://stefan-lesser.com/"
