baseURL = "https://stefan-lesser.com/"
languageCode = "en-us"
title = "Stefan Lesser"
theme = "hugo-lithium-theme"
googleAnalytics = "UA-7357192-1"

tags = ["blog"]
features = ["blog", "google analytics"]
min_version = 0.15

[author]
    name = "Stefan Lesser"
    homepage = "https://stefan-lesser.com/"

[permalinks]
    post = "/:year/:month/:day/:title/"
    page = "/:title/"

[[menu.main]]
    name = "About"
    url = "/about/"
