baseURL = "https://stefan-lesser.com/"
locale = "en-us"
title = "Stefan Lesser"
theme = "hugo-lithium-theme"
features = ["blog"]

[taxonomies]
  category = "categories"
  tag = "tags"
min_version = 0.15
rssLimit = 20

[markup.goldmark.renderer]
    unsafe = true

[author]
    name = "Stefan Lesser"
    homepage = "https://stefan-lesser.com/"

[permalinks]
    post = "/:year/:month/:day/:title/"
    page = "/:title/"

[[menu.main]]
    name = "About"
    url = "/about/"
